site_name: HEP ML Living Review
site_url: https://iml-wg.github.io/HEPML-LivingReview/
nav:
  - Home : index.md
  - Recent: recent.md
  - About: about.md
  - Contribute: contribute.md
  - Resources:
    - Resouces: resources.md
    - Report [PDF]: assets/hepml_review.pdf
  - Cite Us: cite.md

repo_url: https://github.com/iml-wg/HEPML-LivingReview/

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - attr_list

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.expand
    - toc.follow
    - navigation.top
    # - toc.integrate
    - search.share
    - search.suggest
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
